---
language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

branches:
  only:
    - master
    - develop

install: pip install .[dev,test]

script:
  - check-manifest --ignore tests*
  - python setup.py check -m -r -s
  - flake8 .
  - python -m unittest
